// <auto-generated />
using System;

namespace MyNamespace
{
    partial class TestClass_OneField_WithNamespace
    {
        public TestClass_OneField_WithNamespace(Class _classInjected)
        {
            this._classInjected = _classInjected ?? throw new ArgumentNullException(nameof(_classInjected));
        }
    }
}