// <auto-generated />
using System;

partial class TestClass_OneField
{
    public TestClass_OneField(Class _field)
    {
        this._field = _field ?? throw new ArgumentNullException(nameof(_field));
    }
}