// <auto-generated />
using System;

namespace MyNamespace
{
    partial class MyName
    {
        public MyName(Object MyDependentName)
        {
            this.MyDependentName = MyDependentName ?? throw new ArgumentNullException(nameof(MyDependentName));
        }
    }
}