// <auto-generated />
using System;

    partial class TestClass_OneField_OneProperty
    {
        public TestClass_OneField_OneProperty(ClassWithoutInterface _classWithoutInterfaceInjected, ClassWithoutInterface ClassWithoutInterfaceInjected)
        {
            this._classWithoutInterfaceInjected = _classWithoutInterfaceInjected ?? throw new ArgumentNullException(nameof(_classWithoutInterfaceInjected));
            this.ClassWithoutInterfaceInjected = ClassWithoutInterfaceInjected ?? throw new ArgumentNullException(nameof(ClassWithoutInterfaceInjected));
        }
    }