// <auto-generated />
using System;

partial class TestClass_OneField_OneProperty
{
    public TestClass_OneField_OneProperty(Class _field, Class Property)
    {
        this._field = _field ?? throw new ArgumentNullException(nameof(_field));
        this.Property = Property ?? throw new ArgumentNullException(nameof(Property));
    }
}